name: seoptimize
services:
- name: web
  source_dir: /
  github:
    repo: yourusername/seoptimize  # Replace with your actual GitHub repo
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/month - upgrade to basic-xs ($12/month) if needed
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_SUPABASE_URL
    value: your-supabase-project-url  # Replace with your actual Supabase URL
  - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
    value: your-supabase-anon-key  # Replace with your actual Supabase anon key
  - key: ENABLE_LIGHTHOUSE
    value: "true"
  health_check:
    http_path: /
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
